In [1]:
# Dependencies
import pandas as pd
import requests
import json
from pprint import pprint

In [12]:
pd.set_option('display.max_columns', 100)

In [2]:
# Performing a GET Request and saving the 
# API's response within a variable
url = "https://api.spacexdata.com/v3/rockets"
response = requests.get(url)

all_rockets = response.json()
#pprint(all_rockets)

In [ ]:
rocket_df = pd.io.json.json_normalize(all_rockets)

In [13]:
rocket_df.head()

,active,boosters,company,cost_per_launch,country,description,diameter.feet,diameter.meters,engines.engine_loss_max,engines.layout,engines.number,engines.propellant_1,engines.propellant_2,engines.thrust_sea_level.kN,engines.thrust_sea_level.lbf,engines.thrust_to_weight,engines.thrust_vacuum.kN,engines.thrust_vacuum.lbf,engines.type,engines.version,first_flight,first_stage.burn_time_sec,first_stage.cores,first_stage.engines,first_stage.fuel_amount_tons,first_stage.reusable,first_stage.thrust_sea_level.kN,first_stage.thrust_sea_level.lbf,first_stage.thrust_vacuum.kN,first_stage.thrust_vacuum.lbf,flickr_images,height.feet,height.meters,id,landing_legs.material,landing_legs.number,mass.kg,mass.lb,payload_weights,rocket_id,rocket_name,rocket_type,second_stage.burn_time_sec,second_stage.engines,second_stage.fuel_amount_tons,second_stage.payloads.composite_fairing.diameter.feet,second_stage.payloads.composite_fairing.diameter.meters,second_stage.payloads.composite_fairing.height.feet,second_stage.payloads.composite_fairing.height.meters,second_stage.payloads.option_1,second_stage.payloads.option_2,second_stage.reusable,second_stage.thrust.kN,second_stage.thrust.lbf,stages,success_rate_pct,wikipedia
0,False,0,SpaceX,6700000,Republic of the Marshall Islands,The Falcon 1 was an expendable launch system p...,5.5,1.68,0.0,single,1,liquid oxygen,RP-1 kerosene,420,94000,96.0,480,110000,merlin,1C,2006-03-24,169.0,NaN,1,44.3,False,420,94000,480,110000,[https://www.spacex.com/sites/spacex/files/sty...,73.0,22.25,1,None,0,30146,66460,"[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",falcon1,Falcon 1,rocket,378.0,1,3.38,4.9,1.5,11.5,3.5,composite fairing,NaN,False,31,7000,2,40,https://en.wikipedia.org/wiki/Falcon_1
1,True,0,SpaceX,50000000,United States,Falcon 9 is a two-stage rocket designed and ma...,12.0,3.70,2.0,octaweb,9,liquid oxygen,RP-1 kerosene,845,190000,180.1,914,205500,merlin,1D+,2010-06-04,162.0,NaN,9,385.0,True,7607,1710000,8227,1849500,[https://farm1.staticflickr.com/929/2878733830...,229.6,70.00,2,carbon fiber,4,549054,1207920,"[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",falcon9,Falcon 9,rocket,397.0,1,90.00,17.1,5.2,43.0,13.1,dragon,composite fairing,False,934,210000,2,97,https://en.wikipedia.org/wiki/Falcon_9
2,True,2,SpaceX,90000000,United States,With the ability to lift into orbit over 54 me...,39.9,12.20,6.0,octaweb,27,liquid oxygen,RP-1 kerosene,845,190000,180.1,914,205500,merlin,1D+,2018-02-06,162.0,3.0,27,1155.0,True,22819,5130000,24681,5548500,[https://farm5.staticflickr.com/4599/385838292...,229.6,70.00,3,carbon fiber,12,1420788,3125735,"[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",falconheavy,Falcon Heavy,rocket,397.0,1,90.00,17.1,5.2,43.0,13.1,dragon,composite fairing,False,934,210000,2,100,https://en.wikipedia.org/wiki/Falcon_Heavy
3,False,0,SpaceX,7000000,United States,BFR is a privately funded next-generation reus...,30.0,9.00,NaN,None,31,liquid oxygen,liquid methane,1700,382175,NaN,1900,427136,raptor,,2019-12-01,NaN,NaN,31,6700.0,True,128000,28775544,138000,31023634,[https://farm2.staticflickr.com/1861/309341469...,387.0,118.00,4,carbon fiber,4,4400000,9700000,"[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",bfr,Big Falcon Rocket,rocket,NaN,6,1100.00,NaN,NaN,NaN,NaN,Spaceship,composite fairing,True,1900,427136,2,0,https://en.wikipedia.org/wiki/BFR_(rocket)

In [4]:
# rocket_df.count()
# rocket_df.dtypes

In [5]:
rocket_df.columns

Index(['active', 'boosters', 'company', 'cost_per_launch', 'country',
       'description', 'diameter.feet', 'diameter.meters',
       'engines.engine_loss_max', 'engines.layout', 'engines.number',
       'engines.propellant_1', 'engines.propellant_2',
       'engines.thrust_sea_level.kN', 'engines.thrust_sea_level.lbf',
       'engines.thrust_to_weight', 'engines.thrust_vacuum.kN',
       'engines.thrust_vacuum.lbf', 'engines.type', 'engines.version',
       'first_flight', 'first_stage.burn_time_sec', 'first_stage.cores',
       'first_stage.engines', 'first_stage.fuel_amount_tons',
       'first_stage.reusable', 'first_stage.thrust_sea_level.kN',
       'first_stage.thrust_sea_level.lbf', 'first_stage.thrust_vacuum.kN',
       'first_stage.thrust_vacuum.lbf', 'flickr_images', 'height.feet',
       'height.meters', 'id', 'landing_legs.material', 'landing_legs.number',
       'mass.kg', 'mass.lb', 'payload_weights', 'rocket_id', 'rocket_name',
       'rocket_type', 'second_stage.burn_time_sec', 'second_stage.engines',
       'second_stage.fuel_amount_tons',
       'second_stage.payloads.composite_fairing.diameter.feet',
       'second_stage.payloads.composite_fairing.diameter.meters',
       'second_stage.payloads.composite_fairing.height.feet',
       'second_stage.payloads.composite_fairing.height.meters',
       'second_stage.payloads.option_1', 'second_stage.payloads.option_2',
       'second_stage.reusable', 'second_stage.thrust.kN',
       'second_stage.thrust.lbf', 'stages', 'success_rate_pct', 'wikipedia'],
      dtype='object')

In [14]:
rocket_df_final = rocket_df[['id','rocket_name','rocket_id','cost_per_launch','country', 'description'
                            ,'rocket_type', 'active']].copy()
rocket_df_final.head()

,id,rocket_name,rocket_id,cost_per_launch,country,description,rocket_type,active
0,1,Falcon 1,falcon1,6700000,Republic of the Marshall Islands,The Falcon 1 was an expendable launch system p...,rocket,False
1,2,Falcon 9,falcon9,50000000,United States,Falcon 9 is a two-stage rocket designed and ma...,rocket,True
2,3,Falcon Heavy,falconheavy,90000000,United States,With the ability to lift into orbit over 54 me...,rocket,True
3,4,Big Falcon Rocket,bfr,7000000,United States,BFR is a privately funded next-generation reus...,rocket,False

In [6]:
# Performing a GET Request and saving the 
# API's response within a variable
url = "https://api.spacexdata.com/v3/launches"
response = requests.get(url)

all_launches = response.json()
# pprint(all_launches)

In [ ]:
launches_df = pd.io.json.json_normalize(all_launches)

In [15]:
launches_df.head()

,details,flight_number,is_tentative,launch_date_local,launch_date_unix,launch_date_utc,launch_failure_details.altitude,launch_failure_details.reason,launch_failure_details.time,launch_site.site_id,launch_site.site_name,launch_site.site_name_long,launch_success,launch_window,launch_year,links.article_link,links.flickr_images,links.mission_patch,links.mission_patch_small,links.presskit,links.reddit_campaign,links.reddit_launch,links.reddit_media,links.reddit_recovery,links.video_link,links.wikipedia,links.youtube_id,mission_id,mission_name,rocket.fairings,rocket.fairings.recovered,rocket.fairings.recovery_attempt,rocket.fairings.reused,rocket.fairings.ship,rocket.first_stage.cores,rocket.rocket_id,rocket.rocket_name,rocket.rocket_type,rocket.second_stage.block,rocket.second_stage.payloads,ships,static_fire_date_unix,static_fire_date_utc,tbd,telemetry.flight_club,tentative_max_precision,timeline,timeline.beco,timeline.center_core_boostback,timeline.center_core_entry_burn,timeline.center_core_landing,timeline.center_stage_sep,timeline.dragon_bay_door_deploy,timeline.dragon_separation,timeline.dragon_solar_deploy,timeline.engine_chill,timeline.fairing_deploy,timeline.first_stage_boostback_burn,timeline.first_stage_entry_burn,timeline.first_stage_landing,timeline.first_stage_landing_burn,timeline.go_for_launch,timeline.go_for_prop_loading,timeline.ignition,timeline.liftoff,timeline.maxq,timeline.meco,timeline.payload_deploy,timeline.payload_deploy_1,timeline.payload_deploy_2,timeline.payload_deployment,timeline.prelaunch_checks,timeline.propellant_pressurization,timeline.rp1_loading,timeline.seco-1,timeline.seco-2,timeline.second_stage_ignition,timeline.second_stage_restart,timeline.side_core_boostback,timeline.side_core_entry_burn,timeline.side_core_landing,timeline.side_core_sep,timeline.stage1_lox_loading,timeline.stage1_rp1_loading,timeline.stage2_lox_loading,timeline.stage2_rp1_loading,timeline.stage_sep,timeline.webcast_launch,timeline.webcast_liftoff,upcoming
0,Engine failure at 33 seconds and loss of vehicle,1,False,2006-03-25T10:30:00+12:00,1143239400,2006-03-24T22:30:00.000Z,NaN,merlin engine failure,33.0,kwajalein_atoll,Kwajalein Atoll,Kwajalein Atoll Omelek Island,False,0.0,2006,https://www.space.com/2196-spacex-inaugural-fa...,[],https://images2.imgbox.com/40/e3/GypSkayF_o.png,https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png,None,None,None,None,None,https://www.youtube.com/watch?v=0a_00nJ_Y88,https://en.wikipedia.org/wiki/DemoSat,0a_00nJ_Y88,[],FalconSat,NaN,False,False,False,None,"[{'core_serial': 'Merlin1A', 'flight': 1, 'blo...",falcon1,Falcon 1,Merlin A,1.0,"[{'payload_id': 'FalconSAT-2', 'norad_id': [],...",[],1.142554e+09,2006-03-17T00:00:00.000Z,False,None,hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,False
1,Successful first stage burn and transition to ...,2,False,2007-03-21T13:10:00+12:00,1174439400,2007-03-21T01:10:00.000Z,289.0,harmonic oscillation leading to premature engi...,301.0,kwajalein_atoll,Kwajalein Atoll,Kwajalein Atoll Omelek Island,False,0.0,2007,https://www.space.com/3590-spacex-falcon-1-roc...,[],https://images2.imgbox.com/be/e7/iNqsqVYM_o.png,https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png,None,None,None,None,None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,https://en.wikipedia.org/wiki/DemoSat,Lk4zQ2wP-Nc,[],DemoSat,NaN,False,False,False,None,"[{'core_serial': 'Merlin2A', 'flight': 1, 'blo...",falcon1,Falcon 1,Merlin A,1.0,"[{'payload_id': 'DemoSAT', 'norad_id': [], 're...",[],NaN,None,False,None,hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,False
2,Residual stage 1 thrust led to collision betwe...,3,False,2008-08-02T15:34:00+12:00,1217648040,2008-08-02T03:34:00.000Z,35.0,residual stage-1 thrust led to collision betwe...,140.0,kwajalein_atoll,Kwajalein Atoll,Kwajalein Atoll Omelek Island,False,0.0,2008,http://www.spacex.com/news/2013/02/11/falcon-1...,[],https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png,https://images2.imgbox.com/3d/86/cnu0pan8_o.png,None,None,None,None,None,https://www.youtube.com/watch?v=v0w9p3U8860,https://en.wikipedia.org/wiki/Trailblazer_(sat...,v0w9p3U8860,[],Trailblazer,NaN,False,False,False,None,"[{'core_serial': 'Merlin1C', 'flight': 1, 'blo...",falcon1,Falcon 1,Merlin C,1.0,"[{'payload_id': 'Trailblazer', 'norad_id': [],...",[],NaN,None,False,None,hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,False
3,Ratsat was carried to orbit on the first succe...,4,False,2008-09-28T11:15:00+12:00,1222643700,2008-09-28T23:15:00.000Z,NaN,NaN,NaN,kwajalein_atoll,Kwajalein Atoll,Kwajalein Atoll Omelek Island,True,0.0,2008,https://en.wikipedia.org/wiki/Ratsat,[],https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png,https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png,None,None,None,None,None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,dLQ2tZEH6G0,[],RatSat,NaN,False,False,False,None,"[{'core_serial': 'Merlin2C', 'flight': 1, 'blo...",falcon1,Falcon 1,Merlin C,1.0,"[{'payload_id': 'RatSat', 'norad_id': [33393],...",[],1.221869e+09,2008-09-20T00:00:00.000Z,False,None,hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,False
4,None,5,False,2009-07-13T15:35:00+12:00,1247456100,2009-07-13T03:35:00.000Z,NaN,NaN,NaN,kwajalein_atoll,Kwajalein Atoll,Kwajalein Atoll Omelek Island,True,0.0,2009,http://www.spacex.com/news/2013/02/12/falcon-1...,[],https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png,https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png,http://www.spacex.com/press/2012/12/19/spacexs...,None,None,None,None,https://www.youtube.com/watch?v=yTaIDooc8Og,https://en.wikipedia.org/wiki/RazakSAT,yTaIDooc8Og,[],RazakSat,NaN,False,False,False,None,"[{'core_serial': 'Merlin3C', 'flight': 1, 'blo...",falcon1,Falcon 1,Merlin C,1.0,"[{'payload_id': 'RazakSAT', 'norad_id': [35578...",[],NaN,None,False,None,hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,False

In [8]:
# launches_df.count()
# launches_df.dtypes

In [9]:
launches_df.columns

Index(['details', 'flight_number', 'is_tentative', 'launch_date_local',
       'launch_date_unix', 'launch_date_utc',
       'launch_failure_details.altitude', 'launch_failure_details.reason',
       'launch_failure_details.time', 'launch_site.site_id',
       'launch_site.site_name', 'launch_site.site_name_long', 'launch_success',
       'launch_window', 'launch_year', 'links.article_link',
       'links.flickr_images', 'links.mission_patch',
       'links.mission_patch_small', 'links.presskit', 'links.reddit_campaign',
       'links.reddit_launch', 'links.reddit_media', 'links.reddit_recovery',
       'links.video_link', 'links.wikipedia', 'links.youtube_id', 'mission_id',
       'mission_name', 'rocket.fairings', 'rocket.fairings.recovered',
       'rocket.fairings.recovery_attempt', 'rocket.fairings.reused',
       'rocket.fairings.ship', 'rocket.first_stage.cores', 'rocket.rocket_id',
       'rocket.rocket_name', 'rocket.rocket_type', 'rocket.second_stage.block',
       'rocket.second_stage.payloads', 'ships', 'static_fire_date_unix',
       'static_fire_date_utc', 'tbd', 'telemetry.flight_club',
       'tentative_max_precision', 'timeline', 'timeline.beco',
       'timeline.center_core_boostback', 'timeline.center_core_entry_burn',
       'timeline.center_core_landing', 'timeline.center_stage_sep',
       'timeline.dragon_bay_door_deploy', 'timeline.dragon_separation',
       'timeline.dragon_solar_deploy', 'timeline.engine_chill',
       'timeline.fairing_deploy', 'timeline.first_stage_boostback_burn',
       'timeline.first_stage_entry_burn', 'timeline.first_stage_landing',
       'timeline.first_stage_landing_burn', 'timeline.go_for_launch',
       'timeline.go_for_prop_loading', 'timeline.ignition', 'timeline.liftoff',
       'timeline.maxq', 'timeline.meco', 'timeline.payload_deploy',
       'timeline.payload_deploy_1', 'timeline.payload_deploy_2',
       'timeline.payload_deployment', 'timeline.prelaunch_checks',
       'timeline.propellant_pressurization', 'timeline.rp1_loading',
       'timeline.seco-1', 'timeline.seco-2', 'timeline.second_stage_ignition',
       'timeline.second_stage_restart', 'timeline.side_core_boostback',
       'timeline.side_core_entry_burn', 'timeline.side_core_landing',
       'timeline.side_core_sep', 'timeline.stage1_lox_loading',
       'timeline.stage1_rp1_loading', 'timeline.stage2_lox_loading',
       'timeline.stage2_rp1_loading', 'timeline.stage_sep',
       'timeline.webcast_launch', 'timeline.webcast_liftoff', 'upcoming'],
      dtype='object')

In [ ]:
launcher_df_final = launches_df[['rocket.rocket_name','flight_number','rocket.rocket_id','launch_date_utc'  
                                ,'details','flight_number','launch_year']].copy()

In [47]:
launcher_df_final.head()

,rocket_name,launch_pads_id,rocket_id,date_utc,details,launch_pads_id,year
0,Falcon 1,1,falcon1,2006-03-24T22:30:00.000Z,Engine failure at 33 seconds and loss of vehicle,1,2006
1,Falcon 1,2,falcon1,2007-03-21T01:10:00.000Z,Successful first stage burn and transition to ...,2,2007
2,Falcon 1,3,falcon1,2008-08-02T03:34:00.000Z,Residual stage 1 thrust led to collision betwe...,3,2008
3,Falcon 1,4,falcon1,2008-09-28T23:15:00.000Z,Ratsat was carried to orbit on the first succe...,4,2008
4,Falcon 1,5,falcon1,2009-07-13T03:35:00.000Z,None,5,2009

In [46]:
#Rename the Dataframe columns to match the table columns

launcher_df_final.rename(columns={'rocket.rocket_name':'rocket_name'
                                  ,'flight_number':'launch_pads_id'
                                  ,'rocket.rocket_id':'rocket_id'
                                  ,'launch_date_utc':'date_utc'
                                  ,'launch_year':'year'}, 
                                  inplace=True)

In [ ]:
# Performing a GET Request and saving the 
# API's response within a variable
url = "https://api.spacexdata.com/v3/launchpads"
response = requests.get(url)

launch_pads= response.json()
#pprint(launch_pads)

In [ ]:
launch_pads_df = pd.io.json.json_normalize(launch_pads)

In [17]:
launch_pads_df.head()

,attempted_launches,details,id,location.latitude,location.longitude,location.name,location.region,site_id,site_name_long,status,successful_launches,vehicles_launched,wikipedia
0,5,"SpaceX original launch site, where all of the ...",1,9.047721,167.743129,Omelek Island,Marshall Islands,kwajalein_atoll,Kwajalein Atoll Omelek Island,retired,2,[Falcon 1],https://en.wikipedia.org/wiki/Omelek_Island
1,41,"SpaceX primary Falcon 9 launch pad, where all ...",2,28.561857,-80.577366,Cape Canaveral,Florida,ccafs_slc_40,Cape Canaveral Air Force Station Space Launch ...,active,39,[Falcon 9],https://en.wikipedia.org/wiki/Cape_Canaveral_A...
2,17,NASA historic launch pad that launched most of...,4,28.608058,-80.603956,Cape Canaveral,Florida,ksc_lc_39a,Kennedy Space Center Historic Launch Complex 39A,active,17,"[Falcon 9, Falcon Heavy]",https://en.wikipedia.org/wiki/Kennedy_Space_Ce...
3,0,SpaceX original west coast launch pad for Falc...,5,34.644090,-120.593144,Vandenberg Air Force Base,California,vafb_slc_3w,Vandenberg Air Force Base Space Launch Complex 3W,retired,0,[Falcon 1],https://en.wikipedia.org/wiki/Vandenberg_AFB_S...
4,14,SpaceX primary west coast launch pad for polar...,6,34.632093,-120.610829,Vandenberg Air Force Base,California,vafb_slc_4e,Vandenberg Air Force Base Space Launch Complex 4E,active,14,[Falcon 9],https://en.wikipedia.org/wiki/Vandenberg_AFB_S...

In [18]:
launch_pads_df.columns

Index(['attempted_launches', 'details', 'id', 'location.latitude',
       'location.longitude', 'location.name', 'location.region', 'site_id',
       'site_name_long', 'status', 'successful_launches', 'vehicles_launched',
       'wikipedia'],
      dtype='object')

In [57]:
launch_pads_final_df = launch_pads_df[['id', 'location.name', 'location.region', 'status', 'details'
                                      , 'successful_launches']].copy()

In [60]:
launch_pads_final_df.head()

,launch_pads_id,location_name,region,status,details,successful_launches
0,1,Omelek Island,Marshall Islands,retired,"SpaceX original launch site, where all of the ...",2
1,2,Cape Canaveral,Florida,active,"SpaceX primary Falcon 9 launch pad, where all ...",39
2,4,Cape Canaveral,Florida,active,NASA historic launch pad that launched most of...,17
3,5,Vandenberg Air Force Base,California,retired,SpaceX original west coast launch pad for Falc...,0
4,6,Vandenberg Air Force Base,California,active,SpaceX primary west coast launch pad for polar...,14

In [59]:
#Rename the Dataframe columns to match the table columns

launch_pads_final_df.rename(columns={'id':'launch_pads_id'
                                  ,'location.name':'location_name'
                                  ,'location.region':'region'}, 
                                  inplace=True)

In [22]:
from sqlalchemy import create_engine

In [30]:
import pymysql

In [31]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='nancy911',
                             db='customer_db')

In [39]:
# Connect to the Database and insert the data

# PyMySQL
engine = create_engine(f'mysql+pymysql://root:nancy911@localhost/spacex')

In [40]:
engine.table_names()

['launch_pads', 'launcher', 'rockets']

### Load DataFrames into database

In [44]:
rocket_df_final.to_sql(name='rockets', con=engine, if_exists='append', index=False)

In [53]:
launcher_df_final.to_sql(name='launcher', con=engine, if_exists='append', index=False)

In [61]:
launch_pads_final_df.to_sql(name='launch_pads', con=engine, if_exists='append', index=False)